source 'https://rubygems.org'

gem 'grape', '1.1.0'
gem 'rake'
gem 'pry-meta'
gem 'dotenv'
gem 'sequel', '5.12.0'
gem 'pg'
gem 'rack-cors'
gem 'rack-contrib'
gem 'jwt', '2.1.0'
gem 'rest-client'
gem 'bcrypt'
gem 'pry'
